name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dirclass
    permissions:
      id-token: write
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip build
      - run: python -m build
        working-directory: .
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build pack age
        run: |
          python setup.py sdist bdist_wheel  # Using setup.py per request
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1